# Generated by Django 5.0.2 on 2024-02-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='name',
            field=models.CharField(default='', max_length=6, unique=True),
        ),
    ]
